### ISSUE TITLE
Children not mounted before experience chosen

### ISSUE THREAD

**Issue by andrewl913** [GoAheadTours/react-evergage-AB#10]
Getting a client side error:

 `EvergageABTest.js:84 Uncaught TypeError: Cannot read property '0' of undefined
    at EvergageABTest.render (EvergageABTest.js:84)
    at finishClassComponent (react-dom.development.js:10249)
    at updateClassComponent (react-dom.development.js:10226)
    at beginWork (react-dom.development.js:10605)
    at performUnitOfWork (react-dom.development.js:12573)
    at workLoop (react-dom.development.js:12682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at HTMLUnknownElement.wrapped (build.umd.js:1424)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
EvergageABTest.render @ EvergageABTest.js:84
finishClassComponent @ react-dom.development.js:10249
updateClassComponent @ react-dom.development.js:10226
beginWork @ react-dom.development.js:10605
performUnitOfWork @ react-dom.development.js:12573
workLoop @ react-dom.development.js:12682
callCallback @ react-dom.development.js:1299
wrapped @ build.umd.js:1424
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
performWork @ react-dom.development.js:12800
scheduleUpdateImpl @ react-dom.development.js:13185
scheduleUpdate @ react-dom.development.js:13124
enqueueSetState @ react-dom.development.js:9646
ReactComponent.setState @ react.development.js:218
EvergageABTest.checkForExperience @ EvergageABTest.js:48
wrapped @ build.umd.js:1424
setTimeout (async)
(anonymous) @ build.umd.js:1478
EvergageABTest.componentDidMount @ EvergageABTest.js:38
commitLifeCycles @ react-dom.development.js:11505
commitAllLifeCycles @ react-dom.development.js:12294
callCallback @ react-dom.development.js:1299
wrapped @ build.umd.js:1424
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
commitAllWork @ react-dom.development.js:12415
workLoop @ react-dom.development.js:12687
callCallback @ react-dom.development.js:1299
wrapped @ build.umd.js:1424
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
performWork @ react-dom.development.js:12800
scheduleUpdateImpl @ react-dom.development.js:13185
scheduleUpdate @ react-dom.development.js:13124
enqueueSetState @ react-dom.development.js:9646
ReactComponent.setState @ react.development.js:218
onStateChange @ connectAdvanced.js:222
notify @ Subscription.js:30
notifyNestedSubs @ Subscription.js:69
onStateChange @ connectAdvanced.js:219
notify @ Subscription.js:30
notifyNestedSubs @ Subscription.js:69
onStateChange @ connectAdvanced.js:219
dispatch @ createStore.js:186
dispatch @ VM1316:2
(anonymous) @ middleware.js:22
(anonymous) @ index.js:17
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:45
(anonymous) @ action-creators.js:61
Promise resolved (async)
(anonymous) @ action-creators.js:55
(anonymous) @ index.js:11
dispatch @ VM1316:2
getBanner @ container.js:18
fetchBrowsePageBanner @ BrowsePage.jsx:56
componentWillMount @ BrowsePage.jsx:47
callComponentWillMount @ react-dom.development.js:9777
mountClassInstance @ react-dom.development.js:9834
updateClassComponent @ react-dom.development.js:10216
beginWork @ react-dom.development.js:10605
performUnitOfWork @ react-dom.development.js:12573
workLoop @ react-dom.development.js:12682
callCallback @ react-dom.development.js:1299
wrapped @ build.umd.js:1424
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
performWork @ react-dom.development.js:12800
batchedUpdates @ react-dom.development.js:13244
performFiberBatchedUpdates @ react-dom.development.js:1646
stackBatchedUpdates @ react-dom.development.js:1637
batchedUpdates @ react-dom.development.js:1651
batchedUpdatesWithControlledComponents @ react-dom.development.js:1664
dispatchEvent @ react-dom.development.js:1874
wrapped @ build.umd.js:1424`

I think this has to do with not having children mounted during the time the experience is rendered.

**Comment by peterlazzarino** [comment]
This was an issue caused by a test not being migrated to the 2.0.0 version of the package in the client.
